### ISSUE TITLE
Activity rank retention bug

### ISSUE THREAD

**Issue by MediocrityGoggles** [BlackLotusLV/TheCrewCommunity#21]
A user that was previously platinum rank went on a very long hiatus and their activity score zeroed out. This role was not removed when they became active again, and they retained possession of the platinum rank until their activity score rose to the threshold of bronze where it then updated as normal.

**Comment by BlackLotusLV** [comment]
Fixed with https://github.com/BlackLotusLV/TheCrewCommunity/pull/22
